version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environments:
      - DATABASE_URL=postgresql://guardia:guardia123:5433/ms_record

  db:
    image: postgres
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_USER=guardia
      - POSTGRES_PASSWORD=guardia123
      - POSTGRES_DB=ms_record