"""empty message

Revision ID: 020764014c80
Revises: 28cbbe261ff0
Create Date: 2023-07-27 23:14:31.727939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020764014c80'
down_revision = '28cbbe261ff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'data')
    # ### end Alembic commands ###
